# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

- name: Creates directory
  file:
    path: "{{install_files_directory}}"
    state: directory
    mode: '0755'

- name: create install-config.yaml
  template:
    src: ./gcp/templates/install-config-starter.j2
    dest: ./{{install_files_directory}}/install-config.yaml
