- name: Get deployment services rigger
  shell: "kubectl wait deployment -n demo test-rec-services-rigger --for condition=Available=True --timeout=120s"

- name: Get deployment status redis operator
  shell: "kubectl wait deployment -n demo redis-enterprise-operator --for condition=Available=True --timeout=120s"

- name: Wait for last pod
  shell: "kubectl wait pod/test-rec-2 -n demo --for condition=ready --timeout=120s"
