# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---
- name: Create a k8s redis-connect namespace
  kubernetes.core.k8s:
    name: redis-connect
    api_version: v1
    kind: Namespace
    state: present

- name: Create a k8s redis-connect service account
  kubernetes.core.k8s:
    name: redis-connect
    namespace: vault
    api_version: v1
    kind: sa
    state: present

- name: output postgres password
  debug: var=postgres_pw

- name: create redis connect config
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault write database/config/kube-postgres  plugin_name=postgresql-database-plugin allowed_roles="redis-connect" username="postgres" password="{{postgres_pw}}" connection_url="postgresql://postgres:{{postgres_pw}}@mypostgres.postgres.svc:5432/RedisConnect?sslmode=disable"


- name: create redis connect role
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault write database/roles/redis-connect "{{ lookup('template','../template/create_role.json.j2') }}" 
