# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---

- name: Copy script file to postgres pod
  kubernetes.core.k8s_cp:
    namespace: postgres
    pod: mypostgres-1-0
    remote_path: /tmp/postgres_cdc.sql
    local_path: ../../postgres/postgres_cdc.sql

- name: create databaase
  kubernetes.core.k8s_exec:
    namespace: postgres
    pod: mypostgres-1-0
    command: psql postgresql://postgres:{{ postgres_pw }}@localhost:5432 -f /tmp/postgres_cdc.sql
  ignore_errors: true

