# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---

- name: Create an openshift project
  shell: "{{ oc_path }} new-project demo"
  ignore_errors: True

- name: Verify using demo
  shell: "{{ oc_path }} project demo"

- name: Apply bundle
  shell: "{{ oc_path }} apply -f {{ redis_enterprise_github }}/openshift.bundle.yaml"

- name: wait 10 second
  pause:
    seconds: 10

- name: Wait till the redis-enterprise-operator is created
  kubernetes.core.k8s_info:
    kind: deployment
    wait: yes
    name: redis-enterprise-operator
    namespace: demo
    wait_sleep: 10
    wait_timeout: 360

- name: Apply scc.yaml file
  shell: "{{ oc_path }} apply -f {{ redis_enterprise_github }}/openshift/scc.yaml"

- name: add operator permission for rec
  shell: "{{ oc_path }} adm policy add-scc-to-user redis-enterprise-scc-v2 system:serviceaccount:demo:test-rec"

- name: Create a redis enterprise cluster test-rec
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: app.redislabs.com/v1
      kind: RedisEnterpriseCluster
      metadata:
        name: test-rec
        namespace: demo
      spec:
        nodes: 3

- name: wait 10 second
  pause:
    seconds: 10

- name: Wait till the redis enterprise cluster is created
  kubernetes.core.k8s_info:
    kind: rec
    wait: yes
    name: test-rec
    namespace: demo
    wait_sleep: 10
    wait_timeout: 360
