---
- name: ensures temp dir exists
  file:
    path: "temp"
    state: directory

# for active/active need cluster secrets in yaml format
- name: Get cluster password
  shell: "kubectl -n demo get secret/{{rec_name}} -o yaml"
  register: cluster_secrets_yaml

- name: save cluster secrets in yaml
  copy:
    content="{{cluster_secrets_yaml.stdout}}"
    dest="temp/{{rec_name}}-cluster_secrets.yaml"

- name: Get cluster secrets file in json
  shell: "kubectl -n demo get secret/{{rec_name}} -o=json"
  register: cluster_secrets

- name: Get admission cert 
  shell: "kubectl -n demo get secret/admission-tls -o=json"
  register: admission_cert

- name: save cluster secrets
  copy:
    content="{{ cluster_secrets.stdout | from_json }}"
    dest=temp/cluster_secrets.txt

- name: save admission cert
  copy:
    content="{{ (admission_cert.stdout | from_json).data.cert }}"
    dest=temp/admission_cert.txt


- name: cluster username
  set_fact:
     cluster_username: "{{ (cluster_secrets.stdout | from_json).data.username }}"

- name: save cluster username before decode
  copy:
    content="{{ cluster_username }}"
    dest=temp/cluster_un_encoded.txt

- debug: var=cluster_username

- name: cluster user base64
  set_fact:
     cluster_base64_username: "{{ cluster_username | b64decode }}"

- debug: var=cluster_base64_username

- name: save cluster username
  copy:
    content="{{ cluster_base64_username }}"
    dest=temp/cluster_un.txt

- name: cluster password
  set_fact:
     cluster_pw: "{{ (cluster_secrets.stdout | from_json).data.password }}"

- name: save cluster password before decode
  copy:
    content="{{ cluster_pw }}"
    dest=temp/cluster_pw_encoded.txt

- debug: var=cluster_pw

- name: cluster pw base64
  set_fact:
     cluster_base64_pw: "{{ cluster_pw | b64decode }}"

- debug: var=cluster_base64_pw

- name: save cluster password
  copy:
    content="{{ cluster_base64_pw }}"
    dest=temp/cluster_pw.txt
