# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---

- name: "Setting cluster config variables"
  set_fact:
    initial_node_count: 2
    initial_cluster_version: "1.23"

- name: "Connect to cluster (update kubeconfig)"
  shell: "gcloud container clusters get-credentials {{ cluster_name }} --region {{ gcp_region }} --project {{ gcp_project }}"
  when: cluster_state == "present"

- name: Create redis-enterprise cluster
  include_tasks: create-redis-enterprise.yml
  when:
    - create_redis

- name: Create redis databases
  include_tasks: create-databases.yml
  when:
    - create_redis_databases
 
- name: Create postgres 
  include_tasks: create-postgres.yml
  when:
    - create_postgres
 
- name: Create vault 
  include_tasks: create-vault.yml
  when:
    - create_vault
 
- name: Unseal vault 
  include_tasks: unseal-vault.yml
  when:
    - unseal_vault
 
- name: vault plugin copy
  include_tasks: vault-plugin.yml
  when:
    - vault_plugin
 
- name: vault write database config
  include_tasks: vault-write-database.yml
  when:
    - vault_write_database
