# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---

- name: create config map
  kubernetes.core.k8s:
    namespace: redis-connect
    src: ../../redis-connect/redis-connect-config.yml

- name: create redis connect
  kubernetes.core.k8s:
    namespace: redis-connect
    src: ../../redis-connect/vault/redis-connect-start.yaml
