# google.cloud.gcp_container_cluster docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_cluster_module.html
# google.cloud.gcp_container_node_pool docs: https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_container_node_pool_module.html

---
- name: vault operator init
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault operator init -key-shares=1 -key-threshold=1 -format json
  register: vault_init_result

- debug: var=vault_init_result.stdout

- name: create root token
  set_fact:
     root_token: "{{ (vault_init_result.stdout | from_json).root_token }}"

- name: print out root token
  debug:
    var: root_token

- name: create unseal key
  set_fact:
     unseal_keys: "{{ (vault_init_result.stdout | from_json).unseal_keys_b64.0 }}"

- name: print out unseal
  debug:
    var: unseal_keys

- name: save root token file of vault keys
  copy: 
    content: "{{ root_token }}"
    dest: temp/root_token.txt

- name: save root token file of vault keys
  copy: 
    content="{{ unseal_keys }}"
    dest=temp/unseal_keys.txt

- name: save json file of vault keys
  copy: 
    content: "{{ vault_init_result.stdout | from_json }}"
    dest: temp/cluster_keys.json

- name: vault unseal
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault operator unseal "{{ unseal_keys }}"

- name: vault login
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault login "{{ root_token }}"

- name: vault status
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault status
  ignore_errors: true

