- name: Download vault plugin
  ansible.builtin.get_url:
    url: https://github.com/RedisLabs/vault-plugin-database-redis-enterprise/releases/download/v0.1.3/vault-plugin-database-redis-enterprise_0.1.3_linux_amd64
    dest: temp/vault-plugin-database-redis-enterprise_0.1.3_linux_amd64
    mode: '0755'
  when:
    - download_vault_plugin
 
- name: Copy vault plugin to vault pod
  kubernetes.core.k8s_cp:
    namespace: vault
    pod: vault-0
    remote_path: /usr/local/libexec/vault
    local_path: temp/vault-plugin-database-redis-enterprise_0.1.3_linux_amd64

- name: vault chmod
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: chmod 755 /usr/local/libexec/vault/vault-plugin-database-redis-enterprise_0.1.3_linux_amd64

- name: get plugin shasum
  stat:
    path: temp/vault-plugin-database-redis-enterprise_0.1.3_linux_amd64
    checksum_algorithm: sha256 
    get_checksum: yes
  register: shell_stat

- name: print out shasum
  debug: var=shell_stat.stat.checksum

- name: save shasum
  copy:
    content="{{ shell_stat.stat.checksum }}"
    dest=temp/vault-plugin-shasum.txt

- name: vault write plugin
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault write sys/plugins/catalog/database/redisenterprise-database-plugin command=vault-plugin-database-redis-enterprise_0.1.3_linux_amd64 sha256="{{ shell_stat.stat.checksum }}"

- name: vault enable database
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault secrets enable database
