# Run me: ansible-playbook -vv --extra-vars cluster_state=[absent|present] playbook.yml
# Reference: https://docs.ansible.com/ansible/latest/scenario_guides/guide_gce.html

---

- name: Create GKE Cluster using Ansible GCP Library
  hosts: localhost
  gather_facts: no

  roles:
    - gke-test

  environment:
    KUBECONFIG: "{{ KUBECONFIG }}"
