apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-meta
spec:
  memorySize: 500MB
  persistence: "snapshotEvery1Hour"
  databasePort: 12001
  rolesPermissions:
  - type: redis-enterprise
    role: "DB Member"
    acl: "Full Access"
  - type: redis-enterprise
    role: "Admin"
    acl: "Full Access"
  - type: redis-enterprise
    role: "db2"
    acl: "Full Access"
  modulesList: 
  - name: timeseries
    version: 1.8.9
