apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-enterprise-database
spec:
  memorySize: 500MB
  persistence: "snapshotEvery1Hour"
  databasePort: 12000
  rolesPermissions:
  - type: redis-enterprise
    role: "Admin"
    acl: "Full Access"
  - type: redis-enterprise
    role: "DB Member"
    acl: "Full Access"
  - type: redis-enterprise
    role: "db1"
    acl: "Full Access"
