apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-ent5
spec:
  memorySize: 100MB
  persistence: "snapshotEvery1Hour"
  rolesPermissions:
  - type: redis-enterprise
    role: "Admin"
    acl: "Full Access"
  - type: redis-enterprise
    role: "DB Member"
    acl: "Full Access"
