apiVersion: v1
kind: ConfigMap
metadata:
  name: mypostgres-conf
  namespace: postgres

data:

  postgres.conf: |

    # Replication configs
    wal_level=logical
    max_wal_senders=10
    max_replication_slots=10
    track_commit_timestamp=on
